// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/almondoo/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	command2 "github.com/almondoo/golang-ddd-sample/internal/application/cart/command"
	"github.com/almondoo/golang-ddd-sample/internal/application/cart/eventhandler"
	query2 "github.com/almondoo/golang-ddd-sample/internal/application/cart/query"
	"github.com/almondoo/golang-ddd-sample/internal/application/catalog/command"
	"github.com/almondoo/golang-ddd-sample/internal/application/catalog/query"
	command3 "github.com/almondoo/golang-ddd-sample/internal/application/order/command"
	query3 "github.com/almondoo/golang-ddd-sample/internal/application/order/query"
	"github.com/almondoo/golang-ddd-sample/internal/infrastructure/persistence"
	"github.com/almondoo/golang-ddd-sample/internal/presentation/controller"
	"net/http"
)

// Injectors from wire.go:

// このファイルは DI の「設計図」であり、wireinject ビルドタグ付きのため
// 通常の go build / go test には一切含まれない（コンパイル対象は
// wire_gen.go の方）。wire はリフレクションではなくコード生成で DI を
// 行うツールであるため、ここに書いた配線に過不足や型の不一致があれば
// `go run github.com/almondoo/wire/cmd/wire ./cmd/api` の実行時点で
// エラーとして検出できる（実行時に初めて panic する手書き DI や
// リフレクションベースの DI コンテナとの大きな違いである）。
//
// initializeServer は DSN を受け取り、DB 接続からユースケース・
// コントローラ・mux までの依存グラフ全体を組み立てて *http.ServeMux を
// 返す injector（注入器）である。中身は wire.Build の呼び出しだけで、
// 実際の組み立てコードは wire が providers.go の各 provider を解析して
// 自動生成する。
func initializeServer(dsn string) (*http.ServeMux, error) {
	db, err := provideDB(dsn)
	if err != nil {
		return nil, err
	}
	productRepository := persistence.NewProductRepository(db)
	txManager := persistence.NewTxManager(db)
	registerProductUseCase := command.NewRegisterProductUseCase(productRepository, txManager)
	changePriceUseCase := command.NewChangePriceUseCase(productRepository, txManager)
	productQuery := persistence.NewProductQuery(db)
	listProductsUseCase := query.NewListProductsUseCase(productQuery)
	getProductUseCase := query.NewGetProductUseCase(productQuery)
	catalogController := controller.NewCatalogController(registerProductUseCase, changePriceUseCase, listProductsUseCase, getProductUseCase)
	cartRepository := persistence.NewCartRepository(db)
	addItemUseCase := command2.NewAddItemUseCase(cartRepository, txManager)
	removeItemUseCase := command2.NewRemoveItemUseCase(cartRepository, txManager)
	cartQuery := persistence.NewCartQuery(db)
	getCartUseCase := query2.NewGetCartUseCase(cartQuery)
	cartController := controller.NewCartController(addItemUseCase, removeItemUseCase, getCartUseCase)
	orderRepository := persistence.NewOrderRepository(db)
	clearCartOnOrderPlaced := eventhandler.NewClearCartOnOrderPlaced(cartRepository)
	bus := provideEventBus(clearCartOnOrderPlaced)
	placeOrderUseCase := command3.NewPlaceOrderUseCase(orderRepository, cartRepository, productRepository, txManager, bus)
	payOrderUseCase := command3.NewPayOrderUseCase(orderRepository, txManager)
	shipOrderUseCase := command3.NewShipOrderUseCase(orderRepository, txManager)
	cancelOrderUseCase := command3.NewCancelOrderUseCase(orderRepository, txManager)
	orderQuery := persistence.NewOrderQuery(db)
	getOrderUseCase := query3.NewGetOrderUseCase(orderQuery)
	orderController := controller.NewOrderController(placeOrderUseCase, payOrderUseCase, shipOrderUseCase, cancelOrderUseCase, getOrderUseCase)
	serveMux := provideMux(catalogController, cartController, orderController)
	return serveMux, nil
}
