// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/almondoo/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/almondoo/golang-ddd-sample/internal/application/usecase/cart"
	"github.com/almondoo/golang-ddd-sample/internal/application/usecase/catalog"
	"github.com/almondoo/golang-ddd-sample/internal/application/usecase/coupon"
	"github.com/almondoo/golang-ddd-sample/internal/application/usecase/customer"
	"github.com/almondoo/golang-ddd-sample/internal/application/usecase/inventory"
	"github.com/almondoo/golang-ddd-sample/internal/application/usecase/order"
	"github.com/almondoo/golang-ddd-sample/internal/application/usecase/shipping"
	"github.com/almondoo/golang-ddd-sample/internal/infrastructure/persistence"
	"github.com/almondoo/golang-ddd-sample/internal/presentation/controller"
	"net/http"
)

// Injectors from wire.go:

// このファイルは DI の「設計図」であり、wireinject ビルドタグ付きのため
// 通常の go build / go test には一切含まれない（コンパイル対象は
// wire_gen.go の方）。wire はリフレクションではなくコード生成で DI を
// 行うツールであるため、ここに書いた配線に過不足や型の不一致があれば
// `go run github.com/almondoo/wire/cmd/wire ./cmd/api` の実行時点で
// エラーとして検出できる（実行時に初めて panic する手書き DI や
// リフレクションベースの DI コンテナとの大きな違いである）。
//
// initializeServer は DSN を受け取り、DB 接続からユースケース・
// コントローラ・mux までの依存グラフ全体を組み立てて *http.ServeMux を
// 返す injector（注入器）である。中身は wire.Build の呼び出しだけで、
// 実際の組み立てコードは wire が providers.go の各 provider を解析して
// 自動生成する。
func initializeServer(dsn string) (*http.ServeMux, error) {
	db, err := provideDB(dsn)
	if err != nil {
		return nil, err
	}
	productRepository := persistence.NewProductRepository(db)
	txManager := persistence.NewTxManager(db)
	registerProductUseCase := catalog.NewRegisterProductUseCase(productRepository, txManager)
	changePriceUseCase := catalog.NewChangePriceUseCase(productRepository, txManager)
	productQuery := persistence.NewProductQuery(db)
	listProductsUseCase := catalog.NewListProductsUseCase(productQuery)
	getProductUseCase := catalog.NewGetProductUseCase(productQuery)
	catalogController := controller.NewCatalogController(registerProductUseCase, changePriceUseCase, listProductsUseCase, getProductUseCase)
	cartRepository := persistence.NewCartRepository(db)
	addItemUseCase := cart.NewAddItemUseCase(cartRepository, txManager)
	removeItemUseCase := cart.NewRemoveItemUseCase(cartRepository, txManager)
	cartQuery := persistence.NewCartQuery(db)
	getCartUseCase := cart.NewGetCartUseCase(cartQuery)
	cartController := controller.NewCartController(addItemUseCase, removeItemUseCase, getCartUseCase)
	orderRepository := persistence.NewOrderRepository(db)
	customerRepository := persistence.NewCustomerRepository(db)
	stockRepository := persistence.NewStockRepository(db)
	couponRepository := persistence.NewCouponRepository(db)
	placeOrderUseCase := order.NewPlaceOrderUseCase(orderRepository, cartRepository, productRepository, customerRepository, stockRepository, couponRepository, txManager)
	payOrderUseCase := order.NewPayOrderUseCase(orderRepository, txManager)
	shipmentRepository := persistence.NewShipmentRepository(db)
	shipOrderUseCase := order.NewShipOrderUseCase(orderRepository, customerRepository, shipmentRepository, stockRepository, txManager)
	cancelOrderUseCase := order.NewCancelOrderUseCase(orderRepository, stockRepository, couponRepository, txManager)
	orderQuery := persistence.NewOrderQuery(db)
	getOrderUseCase := order.NewGetOrderUseCase(orderQuery)
	orderController := controller.NewOrderController(placeOrderUseCase, payOrderUseCase, shipOrderUseCase, cancelOrderUseCase, getOrderUseCase)
	registerCustomerUseCase := customer.NewRegisterCustomerUseCase(customerRepository, txManager)
	addAddressUseCase := customer.NewAddAddressUseCase(customerRepository, txManager)
	changeDefaultAddressUseCase := customer.NewChangeDefaultAddressUseCase(customerRepository, txManager)
	removeAddressUseCase := customer.NewRemoveAddressUseCase(customerRepository, txManager)
	customerQuery := persistence.NewCustomerQuery(db)
	getCustomerUseCase := customer.NewGetCustomerUseCase(customerQuery)
	customerController := controller.NewCustomerController(registerCustomerUseCase, addAddressUseCase, changeDefaultAddressUseCase, removeAddressUseCase, getCustomerUseCase)
	setStockUseCase := inventory.NewSetStockUseCase(stockRepository, txManager)
	stockQuery := persistence.NewStockQuery(db)
	getStockUseCase := inventory.NewGetStockUseCase(stockQuery)
	inventoryController := controller.NewInventoryController(setStockUseCase, getStockUseCase)
	deliverShipmentUseCase := shipping.NewDeliverShipmentUseCase(shipmentRepository, txManager)
	shipmentQuery := persistence.NewShipmentQuery(db)
	getShipmentUseCase := shipping.NewGetShipmentUseCase(shipmentQuery)
	shippingController := controller.NewShippingController(deliverShipmentUseCase, getShipmentUseCase)
	issueCouponUseCase := coupon.NewIssueCouponUseCase(couponRepository, txManager)
	couponQuery := persistence.NewCouponQuery(db)
	getCouponUseCase := coupon.NewGetCouponUseCase(couponQuery)
	couponController := controller.NewCouponController(issueCouponUseCase, getCouponUseCase)
	serveMux := provideMux(catalogController, cartController, orderController, customerController, inventoryController, shippingController, couponController)
	return serveMux, nil
}
